volumes:
  asciinema_postgres_data_vol:
    external: false

services:
  asciinema-postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: asciinema
      POSTGRES_USER: asciinemauser
      POSTGRES_PASSWORD: asciinemapass
    volumes:
      - asciinema_postgres_data_vol:/var/lib/postgresql/data/
    restart: always
    networks:
      - backend

  asciinema-server:
    build:
      context: ./images/asciinema/asciinema-server
      dockerfile: Dockerfile
      args:
        - ASCIINEMA_IMAGE_TAG=develop
    environment:
      PORT: "4000"
      DATABASE_URL: "postgresql://asciinemauser:asciinemapass@asciinema-postgresql:5432/asciinema"
    depends_on:
      - asciinema-postgresql
      - jupyterhub
    restart: always
    networks:
      - backend

  asciinema-server-base-proxy:
    build:
      context: ./images/asciinema-server-proxy
    depends_on:
      - asciinema-server
    restart: always
    networks:
      - backend

  asciinema-server-proxy:
    image: bitnami/oauth2-proxy:7
    depends_on:
      - jupyterhub
      - asciinema-server-base-proxy
    restart: always
    command:
      - --http-address=0.0.0.0:80
      - --proxy-prefix=/services/asciinema/oauth2
      - --upstream=http://asciinema-server-base-proxy:80/
      - --provider=oidc
      - --provider-display-name=JupyterHub
      - --client-id=${ASCIINEMA_OAUTH_CLIENT_ID:-asciinema_oauth_client_changeme}
      - --client-secret=${ASCIINEMA_OAUTH_CLIENT_SECRET:-asciinema_oauth_secret_changeme}
      - --cookie-secret=${ASCIINEMA_COOKIE_SECRET:-asciinema_cookiesecret_changeme}
      - --cookie-name=_oauth2_proxy_asciinema
      - --redirect-url=https://${SERVER_NAME}/services/asciinema/oauth2/callback
      - --oidc-issuer-url=http://jupyterhub:8000/services/oidcp/internal/
      - --email-domain=*
      - --skip-provider-button=true
    networks:
      - backend

  jupyterhub:
    # Override NBSEARCHDB_* environment variables
    environment:
      ASCIINEMA_ENABLE_OIDC_SERVICE: "1"
      ASCIINEMA_OAUTH_CLIENT_ID: ${ASCIINEMA_OAUTH_CLIENT_ID:-asciinema_oauth_client_changeme}
      ASCIINEMA_OAUTH_CLIENT_SECRET: ${ASCIINEMA_OAUTH_CLIENT_SECRET:-asciinema_oauth_secret_changeme}
      SERVER_NAME: "${SERVER_NAME}"
    volumes:
      - './config/oidc/jupyterhub_config.py:/jupyterhub_config.d/oidc.py:ro'
      - './config/asciinema/jupyterhub_config.py:/jupyterhub_config.d/asciinema.py:ro'
