version: '3.5'

volumes:
  zabbix_postgres_data_vol:
    external: false

services:
  zabbix-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
      POSTGRES_DB: zabbix
    volumes:
      - zabbix_postgres_data_vol:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-6.4-latest
    ports:
      - 162:1162/udp
    restart: always
    networks:
      - backend

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    depends_on:
      - zabbix-postgres
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
      POSTGRES_DB: zabbix
    restart: always
    networks:
      - backend

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    privileged: true
    pid: "host"
    networks:
      - backend

  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:alpine-6.4-latest
    depends_on:
      - zabbix-postgres
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
    restart: always
    networks:
      - backend

  zabbix-web-proxy:
    build:
      context: ./images/zabbix-web-proxy
    depends_on:
      - zabbix-web
    restart: always
    networks:
      - backend

  jupyterhub:
    volumes:
      - './config/zabbix/jupyterhub_config.py:/jupyterhub_config.d/zabbix.py:ro'

